name: "Publish Release"
on:
  push:
    branches: [main]
    tags: ["v*"]
jobs:

  publish-images:
    uses: ./.github/workflows/reusable-publish-images.yaml
    with:
      publish_bundle: true

  operator-hub-prod-release:
    needs: publish-images
    uses: ./.github/workflows/reusable-operator-hub-release.yaml
    with:
      org: redhat-openshift-ecosystem
      repo: community-operators-prod
      branch: ${{ github.ref }}
      oprepo: ${{ github.repository }}
      bundletype: openshift
    secrets:
      TEMPOOPERATORBOT_GITHUB_TOKEN: ${{ secrets.TEMPOOPERATORBOT_GITHUB_TOKEN }}

  operator-hub-community-release:
    needs: publish-images
    uses: ./.github/workflows/reusable-operator-hub-release.yaml
    with:
      org: k8s-operatorhub
      repo: community-operators
      branch: ${{ github.ref }}
      oprepo: ${{ github.repository }}
      bundletype: community
    secrets:
      TEMPOOPERATORBOT_GITHUB_TOKEN: ${{ secrets.TEMPOOPERATORBOT_GITHUB_TOKEN }}
