name: "Release"
on: [push]
jobs:
  release:
#    if: github.event.pusher.name == "github-actions' && startsWith(github.event.pull_request.base.ref, 'refs/heads/release/')
    runs-on: ubuntu-22.04
    steps:
    - name: Determine event
      id: event
      run: echo "Branch=${{ github.event_name }}"

    - name: Determine Branch
      id: branch
      run: echo "Branch=${{ github.event.pull_request.base.ref }}"

    - name: Determine user
      id: user
      run: echo "User=${{ github.event.pusher.name }}"


    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.20"
    - uses: actions/checkout@v4

    - name: "generate release resources"
      run: make release-artifacts
      env:
        IMG_PREFIX: ghcr.io/${{ github.repository }}

    - name: "create the release in GitHub"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        OPERATOR_VERSION=$(git describe --tags | sed 's/^v//')
        awk '/^## / {v=$2} v == "'${OPERATOR_VERSION}'" && !/^## / {print}' CHANGELOG.md > RELEASE_NOTES.md
        gh release create \
            -t "Release v${OPERATOR_VERSION}" \
            -F RELEASE_NOTES.md \
            "v${OPERATOR_VERSION}" \
            'dist/tempo-operator.yaml#Installation manifest for Kubernetes' \
